apiVersion: apps/v1
kind: Deployment

metadata:
  name: super-mario
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: super-mario

  template:
    metadata:
      labels:
        app: super-mario

    spec:
      containers:
      - name: super-mario

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        ports:
        - containerPort: 8080

        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}

          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}

        readinessProbe:
          httpGet:
            path: /
            port: 8080

          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /
            port: 8080

          initialDelaySeconds: 15
          periodSeconds: 20
